### PR TITLE
add types, remove Engine, add tests, hook up Github Actions

### PR DESCRIPTION
**Pull request by tomasc**

### CODE REVIEW

**Comment by tomasc** [comment]
@asgerb I have refined the gem as well as the components

Could you please hook up Travis? The config file is there, and tests pass locally on `bundle exec rake`

Next step would be to add the remaining components from Vime: https://vimejs.com

Thanks!

**Comment by tomasc** [comment]
BTW some of the changes are breaking as I have name-spaced the components to follow Vime's conventions

**Comment by asgerb** [comment]
@tomasc awesome, I'll take a look 🙂

One small thing: I use GitHub Actions usually and have no experience with Travis.
Would you be fine with me setting that up instead?

**Comment by tomasc** [comment]
np, go ahead @asgerb 
I am pushing few more refinements right now
we are still missing some components under Controls, Settings, and Time – help finishing that would be appreciated!

**Comment by tomasc** [comment]
BTW I thought perhaps we could give this gem a version that corresponds with the Vime.js version?

**Comment by asgerb** [comment]
Cool, I'm a bit tied up at the moment, unfortunately, but tomorrow I should have some time to take a look. Otherwise, I think it all looks super good.

One thing I thought when first doing these, was to perhaps not set defaults on the component's options. Vime has defaults for everything and duplicating them on our end too feels unnecessary? If they change a default, then we will have to do it as well. What do you think?

**Comment by tomasc** [comment]
@asgerb I can go either way
I like them there is as the gem becomes somewhat self-documented.
And if Vime changes, we might need to change other things than the defaults anyway, so it does not bother me too much having the defaults included.

**Comment by asgerb** [comment]
OK, gotcha, let's leave them there 👍 

I'll take a look tomorrow and try and add the remaining things + GitHub Actions.
I guess I can just piggyback on this PR?

**Comment by tomasc** [comment]
yep – it's almost there!

**Comment by asgerb** [comment]
👋 @tomasc, looks like you were faster than me!
Any missing components I can add?

**Comment by tomasc** [comment]
@asgerb I think some of the settings are still missing

**Comment by asgerb** [comment]
Cool, I have some time now to jump on it. The [core/embed](https://vimejs.com/components/core/embed) component is also missing, should we skip the [core/playground](https://vimejs.com/components/core/playground) one or is that nice to have too?

**Comment by tomasc** [comment]
@asgerb yep let's have it all!

**Comment by asgerb** [comment]
@tomasc how would you do the `provider` attribute for [Core::Playground](https://vimejs.com/components/core/playground)?
It's an enum of strings, but do you think it's really passed as `provider="Provider.Audio"`?
Seems a bit strange, I would assume it's `provider="audio"` but they don't have an example, unfortunately.

**Comment by tomasc** [comment]
@asgerb skip the Playground ;-)

**Comment by asgerb** [comment]
Will just add it as they have it in the docs, then we can fix it if it's broken 👀
It's a nice-to-have anyways

**Comment by tomasc** [comment]
okeoke

**Comment by tomasc** [comment]
@asgerb I think we are done. We need to decide how to version this and then we can release?

**Comment by tomasc** [comment]
@asgerb any chance to have this wrapped up and released? would help a lot. thanks!

**Review by asgerb — APPROVED** [review]

**Comment by tomasc** [comment]
Thanks @asgerb !

**Pull request merged**
